### ISSUE TITLE
ksyaml outputs empty string

### ISSUE THREAD

**Issue by Ghibranalj** [bukan-kambing/ks-yaml#11]
With the following yaml ksyaml outputs empty :(

```yaml
# This uses kambing style yaml

# Colors (Material Theme)
colors: {
    # Default colors
    primary: { background: "0x212121", foreground: "0xc4c7d1" },
    # Normal colors
    normal:
      {
        black: "0x666666",
        red: "0xf57373",
        green: "0xc3e88d",
        yellow: "0xf7eb95",
        blue: "0x80cbc4",
        magenta: "0xff2f90",
        cyan: "0xaeddff",
        white: "0xffffff",
      },
    # Bright colors
    bright:
      {
        black: "0x5a5860",
        red: "0xf57373",
        green: "0xc3e88d",
        yellow: "0xf7eb95",
        blue: "0x7dc6bf",
        magenta: "0x6c71c4",
        cyan: "0x35434d",
        white: "0xffffff",
      },
  }

window:
  {
    padding: { x: 12, y: 12, dynamic_padding: false },

    opacity: 1.0,
    title: "Terminal",
  }

font:
  {
    normal: { family: Source Code Pro, style: semi-light },

    bold: { family: Source Code Pro, style: Regular },

    italic: { family: Source Code Pro, style: Italic },

    size: 11.0,

    offset: { x: 0, y: 1 },
  }

cursor: {
    # this is cursor
    style: beam,
  }
```
